output if we are trying to commit, plus note on how this works

diff --git a/.github/workflows/autoblack.yml b/.github/workflows/autoblack.yml
--- a/.github/workflows/autoblack.yml
+++ b/.github/workflows/autoblack.yml
@@ -18,6 +18,8 @@ jobs:
         run: |
           git config user.name "$(git log -n 1 --pretty=format:%an)"
           git config user.email "$(git log -n 1 --pretty=format:%ae)"
-          git diff-index --quiet HEAD || (git commit -am 'lint with black' && git push -f)
+          # short-circuit if we have no changes, otherwise attempt to commit and push
+          # should only fail on forks, in which case contributors will need to manually run black, commit, and push
+          git diff-index --quiet HEAD || (echo "Attempting to commit changes" && git commit -am 'lint with black' && git push -f)
       - name: Run black --check .
         run: python3 -m black --check .
